 apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: backoffice-be
   annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/rewrite-target: /$1
 spec:
   rules:
   - host: api.backoffice.local
     http:
       paths:
       - path: /(.*)
         backend:
           serviceName: backoffice-be
           servicePort: 8080
